# © 2024 Cemberk. All rights reserved.
name: "Fork Maintenance System"
description: "A GitHub Action to maintain forked repositories by checking for misspellings, resolving merge conflicts, running regression triage, and providing code suggestions."
author: "Cemberk"


inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  upstream_repo:
    description: "URL of the upstream repository"
    required: true
  schedule_json:
    description: "Schedule JSON containing upstream and downstream release branches"
    required: true
  pr_branch_prefix:
    description: "Prefix for the PR branch name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      shell: bash

    - name: Fetch schedule JSON
      run: echo '${{ inputs.schedule_json }}' > schedule.json
      shell: bash

    - name: Extract branch information
      id: extract_branches
      run: |
        export UPSTREAM_MAIN=$(jq -r '.upstream_main_branch' schedule.json)
        export UPSTREAM_RELEASE=$(jq -r '.upstream_release_branch' schedule.json)
        export DOWNSTREAM_TESTING=$(jq -r '.downstream_testing_branch' schedule.json)
        export DOWNSTREAM_DEVELOP=$(jq -r '.downstream_develop_branch' schedule.json)
        export COMMITS=$(jq -r '.commits[]' schedule.json)
        echo "UPSTREAM_MAIN=$UPSTREAM_MAIN" >> $GITHUB_ENV
        echo "UPSTREAM_RELEASE=$UPSTREAM_RELEASE" >> $GITHUB_ENV
        echo "DOWNSTREAM_TESTING=$DOWNSTREAM_TESTING" >> $GITHUB_ENV
        echo "DOWNSTREAM_DEVELOP=$DOWNSTREAM_DEVELOP" >> $GITHUB_ENV
        echo "COMMITS=$COMMITS" >> $GITHUB_ENV
      shell: bash
    
    - name: Add upstream remote
      run: |
        git remote add upstream ${{ inputs.upstream_repo }}
      shell: bash
    
    - name: Fetch upstream changes
      run: git fetch upstream
      shell: bash
    
    - name: Create new branch
      run: |
        git checkout -b ${{ inputs.pr_branch_prefix }}-$(date +%Y%m%d)
      shell: bash

    - name: Create new branch from upstream release
      run: |
        git checkout upstream/$UPSTREAM_RELEASE
        git checkout -b ${{ inputs.pr_branch_prefix }}-$(date +%Y%m%d)
      shell: bash

    - name: Attempt to merge upstream main into new branch
      run: |
        git merge upstream/$UPSTREAM_MAIN || true
      shell: bash

    - name: Check for merge conflicts
      id: check_conflicts
      run: |
        if git ls-files -u | grep -q '^'; then
          echo "Merge conflicts detected."
          echo "conflicts=true" >> $GITHUB_ENV
        else
          echo "No merge conflicts."
          echo "conflicts=false" >> $GITHUB_ENV
      shell: bash

    - name: Commit merge
      if: env.conflicts == 'false'
      run: |
        git add .
        git commit -m "Merged upstream main into ${{ inputs.pr_branch_prefix }} branch from $UPSTREAM_RELEASE"
        git push origin HEAD:${{ inputs.pr_branch_prefix }}-$(date +%Y%m%d)
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

      
    - name: Create Pull Request
      if: env.conflicts == 'false'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ inputs.github_token }}
        base: ${{ inputs.internal_branch }}
        head: ${{ inputs.pr_branch_prefix }}-$(date +%Y%m%d)
        title: "Automated PR: Merge upstream/${ UPSTREAM_RELEASE } into ${ DOWNSTREAM_DEVELOP }"
        body: "This PR was created automatically by the Fork Maintenance System to merge changes from upstream/${{ inputs.upstream_branch }} into ${{ inputs.internal_branch }}."
        draft: false

    - name: Run reviewdog to suggest conflict resolutions
      if: env.conflicts == 'true'
      uses: reviewdog/action-suggester@v1
      with:
        github_token: ${{ inputs.github_token }}
        tool_name: 'merge-conflict-suggester'
        level: 'warning'
        filter_mode: 'diff_context'
        fail_on_error: 'false'
        cleanup: 'true'


# Example schedule.json
# {
#   "upstream_main_branch": "main",
#   "upstream_release_branch": "release-v1.0",
#   "downstream_testing_branch": "v6.3testing",
#   "downstream_develop_branch": "develop",
#   "commits": [
#     "abcd1234",
#     "efgh5678"
#   ]
# }


    
#  regression_triage_test_script:
#    description: "triage script for unit tests"
#    required: true

#    - name: Run regression triage
#      run: |
#        chmod +x ${{ inputs.regression_triage_test_script }}
#        ./${{ inputs.regression_triage_test_script }}
#      env:
#        GITHUB_TOKEN: ${{ inputs.github_token }}
