name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build NVIDIA Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:nvidia-latest -f Dockerfile.nvidia .

    - name: Push NVIDIA Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:nvidia-latest

    - name: Build AMD Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:amd-latest -f Dockerfile.amd .

    - name: Push AMD Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:amd-latest

    - name: Verify NVIDIA Docker image
      run: |
        docker pull ghcr.io/${{ github.repository }}:nvidia-latest
        docker images ghcr.io/${{ github.repository }}:nvidia-latest

    - name: Verify AMD Docker image
      run: |
        docker pull ghcr.io/${{ github.repository }}:amd-latest
        docker images ghcr.io/${{ github.repository }}:amd-latest
